const CONFIG={
 cbeHolder:"Guesh Gebreabzgi",
 companyHolder:"ETCARE Beauty Products Sales P.L.C.",
 whatsappNumber:"251923493781",
 callNumber:"0923493781",
 telegram:"Gg16A",
 facebook:"https://www.facebook.com/shiremarketlink",
 telebirrGuide:"https://www.ethiotelecom.et/telebirr/telebirr/",
 cbeGuide:"https://combanketh.et/ways-of-banking/mobile-banking"
};
const products=[
 {id:"bio9",name:"Bio9 — Intensive Hair Growth & Scalp Therapy",price:999,image:"assets/bio9.jpg",cert:"100% Pure Organic Extracts • Clinically Tested",benefits:["Deeply nourishes the hair follicles","Helps reduce hair shedding","Helps eliminate dandruff","Supports new hair growth","Rosemary, Black Cumin Seed, Castor & Clove oils"],howto:"Apply a few drops directly to the scalp and massage gently for 5 minutes. Leave for at least 2 hours or overnight before washing. Use 3 times a week."},
 {id:"albent",name:"Albent — Advanced Clarifying Clay Mask",price:899,image:"assets/albent-product.jpg",cert:"100% Organic Certified • Clinically Tested & Approved",benefits:["Pulls out deep-pore impurities","Helps control excess sebum","Helps minimize the appearance of pores","Helps improve the appearance of acne and dark spots","Pure Bentonite Clay + soothing Aloe Vera"],howto:"Apply a thin layer to a clean face. Leave for 10–15 minutes until dry, then rinse gently with lukewarm water. Use 2–3 times a week."},
 {id:"sheba",name:"Sheba Soap — Ultimate Nourishing Bar",price:1099,image:"assets/sheba-soap.jpg",cert:"100% Plant-Based • No Animal Fats",benefits:["Purifies sensitive skin","Maintains natural moisture","Leaves skin soft and glowing","60% premium plant oils including Shea Butter, Olive Oil & Aloe Vera","Natural detoxifiers including Bamboo Charcoal"],howto:"Lather between wet hands and massage gently over face and body morning and night. Rinse thoroughly."},
 {id:"alco",name:"ALCO Shampoo & Conditioner — Deep Damage Repair Duo",price:1299,image:"assets/alco-shampoo.jpg",cert:"100% Natural Oils • Clinically Tested",benefits:["Targets chemically treated, dry and brittle hair","Deep hydration","Helps repair damaged-looking hair","Shine and smooth detangling","Aloe Vera, Coconut Oil & Castor Oil"],howto:"Apply shampoo to wet hair, massage and rinse. Follow with conditioner, focusing on the ends; leave for 3 minutes, then rinse."},
 {id:"og",name:"OG — Ultimate Strength & Anti-Breakage Serum",price:1199,image:"assets/og-castor.jpg",cert:"100% Bio-Organic Ingredients • Tested",benefits:["Helps hydrate and moisturize hair","Helps protect the hair growth barrier","Purifies the scalp","Helps hair look healthier","White Eucalyptus (ነጭ ባህርዛፍ) & Castor Oil"],howto:"Apply a few drops to dry or damp hair daily, focusing on the lengths and ends."}
];
const categoryData={
 property:{title:"Houses & Land",intro:"Choose whether you are buying or selling, then complete the relevant details once. Your submission can be prepared for review and social sharing.",choices:[['seller','I am a Seller','I want to list a house or land for sale.'],['buyer','I am a Buyer','I am looking for a house or land to buy.']]},
 cars:{title:"Cars for Sale",intro:"List a vehicle for sale or tell Trust Market exactly what vehicle you are looking for.",choices:[['seller','I am a Seller','I want to sell a vehicle.'],['buyer','I am a Buyer','I am looking for a vehicle.']]},
 furniture:{title:"Furniture & Electronics",intro:"Create a clear listing for home or office items, or send your buying request.",choices:[['seller','I am a Seller','I want to sell furniture or electronics.'],['buyer','I am a Buyer','I am looking for furniture or electronics.']]},
 jobs:{title:"Jobs & Opportunities",intro:"Post an opportunity or tell us the work you are looking for.",choices:[['seller','I have an Opportunity','I want to post a job or opportunity.'],['buyer','I am Looking for Work','I am looking for a job or opportunity.']]},
 services:{title:"Professional Services",intro:"Offer your service or find a provider. Give enough detail for a useful response.",choices:[['seller','I Offer a Service','I want to list my professional service.'],['buyer','I Need a Service','I am looking for a service provider.']]}
};
let cart=JSON.parse(localStorage.getItem("trust_market_cart")||"[]");
let reviews=JSON.parse(localStorage.getItem("trust_market_reviews")||"[]");
let currentCategory="";
const t={en:{navHome:"Home",navMarket:"Marketplace",navBusiness:"Business",navEtcare:"ETCARE",navReviews:"Reviews",navContact:"Contact",cart:"Cart"},ti:{navHome:"መጀመርታ",navMarket:"ዕዳጋ",navBusiness:"ቢዝነስ",navEtcare:"ETCARE",navReviews:"ግምገማ",navContact:"ርክብ",cart:"ጋሪ"},am:{navHome:"መነሻ",navMarket:"ገበያ",navBusiness:"ንግድ ዕድል",navEtcare:"ETCARE",navReviews:"ግምገማ",navContact:"ያግኙን",cart:"ጋሪ"},ar:{navHome:"الرئيسية",navMarket:"السوق",navBusiness:"فرصة عمل",navEtcare:"ETCARE",navReviews:"التقييمات",navContact:"اتصل بنا",cart:"السلة"},fr:{navHome:"Accueil",navMarket:"Marché",navBusiness:"Business",navEtcare:"ETCARE",navReviews:"Avis",navContact:"Contact",cart:"Panier"}};
function money(n){return Number(n).toLocaleString()+" ETB"}
function esc(s){return String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const x=document.getElementById("toast");x.textContent=msg;x.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove("show"),2400)}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast("Copied")).catch(()=>toast("Copy not available"))}
function toggleMenu(){document.getElementById("mainNav").classList.toggle("open")}
function shareLinks(url,title){const text=encodeURIComponent(title);const u=encodeURIComponent(url);return{facebook:`https://www.facebook.com/sharer/sharer.php?u=${u}`,whatsapp:`https://wa.me/?text=${text}%20${u}`,telegram:`https://t.me/share/url?url=${u}&text=${text}`}}
async function nativeShare({title,text,url,image}){
 try{
  if(navigator.share){
   const data={title,text,url};
   if(image){try{const r=await fetch(image);const b=await r.blob();const ext=b.type.includes("png")?"png":"jpg";const f=new File([b],`${title.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}.${ext}`,{type:b.type||"image/jpeg"});if(navigator.canShare?.({files:[f]}))data.files=[f]}catch(e){}}
   await navigator.share(data); return true;
  }
 }catch(e){if(e?.name!=="AbortError")toast("Sharing was cancelled or unavailable")}
 return false;
}
async function sharePage(method){const url=window.location.href.split("#")[0];const title="Trust Market — Buy, Sell, Grow & Connect";if(method==="native"){if(await nativeShare({title,text:title,url,image:"assets/hero-loft.jpg"}))return}if(method==="copy"){copyText(url);return}const links=shareLinks(url,title);window.open(links[method],"_blank","noopener,noreferrer")}
async function shareProduct(i,method){const p=products[i];const url=window.location.href.split("#")[0]+"#product-"+p.id;const text=`🌿 ${p.name}\n💰 Price: ${money(p.price)}\n✨ Benefits:\n• ${p.benefits.join("\n• ")}\n\nTrust Market`;if(method==="native"){if(await nativeShare({title:p.name,text,url,image:p.image}))return}if(method==="copy"){copyText(url);return}const links=shareLinks(url,text);window.open(links[method],"_blank","noopener,noreferrer")}
function renderProducts(){document.getElementById("productGrid").innerHTML=products.map((p,i)=>`<article class="product" id="product-${p.id}"><button class="image-button" onclick="openImage('${p.image}','${esc(p.name).replace(/'/g,"\\'")}')"><img class="product-img" src="${p.image}" alt="${esc(p.name)}"></button><div class="product-body"><div class="badges"><span class="badge">✓ Clinically Tested</span><span class="badge">✓ Certified</span></div><h3>${esc(p.name)}</h3><div class="price">${money(p.price)}</div><div class="product-share"><span>Share product</span><button onclick="shareProduct(${i},'native')" aria-label="Share ${esc(p.name)}">↗</button><button onclick="shareProduct(${i},'facebook')" aria-label="Facebook">f</button><button onclick="shareProduct(${i},'whatsapp')" aria-label="WhatsApp">W</button><button onclick="shareProduct(${i},'telegram')" aria-label="Telegram">✈</button></div><p class="cert-line">${esc(p.cert)}</p><h4 class="benefit-title">Benefits</h4><ul class="benefits">${p.benefits.map(b=>`<li>${esc(b)}</li>`).join("")}</ul><details class="howto"><summary>How to use</summary><p>${esc(p.howto)}</p></details><div class="product-controls"><button onclick="adjustPageQty(${i},-1)">−</button><input id="pq${i}" type="number" min="1" value="1" aria-label="Quantity"><button onclick="adjustPageQty(${i},1)">+</button><span>quantity</span></div><div class="product-actions"><button class="small-btn add" onclick="addProduct(${i})">Add to Cart</button><button class="small-btn buy" onclick="buyProduct(${i})">Buy Now</button></div></div></article>`).join("")}
function adjustPageQty(i,d){const x=document.getElementById("pq"+i);x.value=Math.max(1,(+x.value||1)+d)}
function addProduct(i){const q=Math.max(1,+document.getElementById("pq"+i).value||1),p=products[i],f=cart.find(x=>x.id===p.id);if(f)f.qty+=q;else cart.push({id:p.id,name:p.name,price:p.price,qty:q});saveCart();toast("Added to cart");location.hash="cart"}
function buyProduct(i){const q=Math.max(1,+document.getElementById("pq"+i).value||1);openPayment(products[i].id,q)}
function saveCart(){localStorage.setItem("trust_market_cart",JSON.stringify(cart));renderCart()}
function renderCart(){const count=cart.reduce((a,x)=>a+x.qty,0),total=cart.reduce((a,x)=>a+x.price*x.qty,0);document.getElementById("cartCount").textContent=count;document.getElementById("summaryItems").textContent=count;document.getElementById("cartTotal").textContent=money(total);document.getElementById("cartItems").innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-line"><span><b>${esc(x.name)}</b><br><small>${x.qty} × ${money(x.price)}</small></span><b>${money(x.qty*x.price)} <button onclick="removeCart(${i})">Remove</button></b></div>`).join(""):"<p class='empty'>Your cart is empty. Add an ETCARE product to begin.</p>";document.getElementById("orderDetails").value=cart.map(x=>`${x.name} × ${x.qty} — ${money(x.qty*x.price)}`).join("\n")||""}
function removeCart(i){cart.splice(i,1);saveCart()}
function setFocus(target){document.body.classList.add("focus-active");document.querySelectorAll("main > section").forEach(s=>s.classList.remove("focus-visible"));document.getElementById(target)?.classList.add("focus-visible");window.scrollTo({top:0,behavior:"smooth"})}
function closeFocus(){document.body.classList.remove("focus-active");document.querySelectorAll("main > section").forEach(s=>s.classList.remove("focus-visible"));document.getElementById("marketplace")?.scrollIntoView({behavior:"smooth"});history.replaceState(null,"","#marketplace")}
function openEtcare(){document.getElementById("categoryArea").classList.add("hidden");setFocus("etcare");history.replaceState(null,"","#etcare")}
function openBusinessFocus(){document.getElementById("categoryArea").classList.add("hidden");setFocus("business");history.replaceState(null,"","#business")}
function openCategory(key){currentCategory=key;const d=categoryData[key];document.getElementById("categoryKicker").textContent=key.toUpperCase();document.getElementById("categoryTitle").textContent=d.title;document.getElementById("categoryIntro").textContent=d.intro;document.getElementById("choiceGrid").innerHTML=d.choices.map(c=>`<button class="choice-card" onclick="showCategoryForm('${key}','${c[0]}')"><span class="choice-check">○</span><div><strong>${c[1]}</strong><small>${c[2]}</small></div><b>→</b></button>`).join("");document.getElementById("categoryPanel").innerHTML="<div class='panel-empty'><b>Choose Buyer or Seller</b><br><small>Only the selected category will stay in focus. Your personal phone is kept private from public listings.</small></div>";document.getElementById("categoryArea").classList.remove("hidden");setFocus("categoryArea");history.replaceState(null,"","#"+key)}
function closeCategory(){document.getElementById("categoryArea").classList.add("hidden");closeFocus();history.replaceState(null,"","#marketplace")}
function field(label,name,placeholder="",type="text",required=true){return `<label>${label}<input name="${name}" type="${type}" ${required?"required":""} placeholder="${placeholder}"></label>`}
function showCategoryForm(key,mode){const seller=mode==="seller";const title=categoryData[key].title;let fields="";
 if(key==="property")fields=seller?field("Listing type","listingType","House / Land")+field("Location","location","Area / city")+field("Price","price","ETB","number")+field("Property size","size","e.g. 20 × 30 m")+field("House type / land use","type","e.g. villa, compound, residential land")+field("Number of rooms","rooms","e.g. 3", "number",false)+field("Bedrooms","bedrooms","e.g. 2","number",false)+field("Bathrooms","bathrooms","e.g. 2","number",false)+field("Floors","floors","e.g. 2","number",false)+field("Finishing / condition","condition","e.g. new, furnished, unfinished", "text",false)+field("Wall / fence","wall","Describe wall or fence", "text",false)+field("Glass / windows","glass","Describe windows / glass", "text",false)+field("Additional details","details","Anything important about the property", "text",false):field("What are you looking for?","lookingFor","House or land")+field("Preferred location","location","Area / city")+field("Budget","budget","ETB", "number")+field("Property size / type","size","What size or type do you need?")+field("Rooms / features","features","Rooms, wall, yard, etc.","text",false)+field("Additional details","details","Anything else", "text",false);
 if(key==="cars")fields=seller?field("Make / model","model","e.g. Toyota Corolla")+field("Year","year","2020","number")+field("Price","price","ETB","number")+field("Location","location","Area / city")+field("Mileage","mileage","km","number",false)+field("Condition","condition","Describe condition", "text",false)+field("Color","color","Color", "text",false)+field("Additional details","details","Important vehicle details", "text",false):field("Vehicle wanted","model","Make / model")+field("Preferred year","year","e.g. 2020","number",false)+field("Budget","budget","ETB","number")+field("Preferred location","location","Area / city")+field("Requirements","requirements","Condition, transmission, fuel, etc.")+field("Additional details","details","Anything else", "text",false);
 if(key==="furniture")fields=seller?field("Item","item","e.g. sofa, TV, refrigerator")+field("Price","price","ETB","number")+field("Location","location","Area / city")+field("Condition","condition","New / used")+field("Brand / model","brand","Brand or model", "text",false)+field("Additional details","details","Measurements, accessories, etc.","text",false):field("Item wanted","item","Furniture or electronics")+field("Budget","budget","ETB","number")+field("Preferred location","location","Area / city")+field("Condition wanted","condition","New / used / either", "text",false)+field("Requirements","requirements","Size, brand, features, etc.")+field("Additional details","details","Anything else","text",false);
 if(key==="jobs")fields=seller?field("Job / opportunity title","title","Role or opportunity")+field("Organization / business","organization","Name", "text",false)+field("Location","location","Area / city")+field("Salary / terms","salary","Salary or terms", "text",false)+field("Requirements","requirements","Skills / qualifications")+field("How to apply","apply","Contact or application details")+field("Additional details","details","Anything else","text",false):field("Work wanted","title","Role or type of work")+field("Preferred location","location","Area / city")+field("Skills","skills","Skills and experience")+field("Expected pay","salary","Expected pay", "text",false)+field("Availability","availability","When you can start", "text",false)+field("Additional details","details","Anything else","text",false);
 if(key==="services")fields=seller?field("Service","service","What service do you offer?")+field("Location","location","Area / city")+field("Price / starting price","price","ETB or quote", "text",false)+field("Experience / qualifications","experience","Describe experience")+field("Contact preference","contactPref","Phone / WhatsApp / Telegram")+field("Additional details","details","Anything else","text",false):field("Service needed","service","What do you need?")+field("Location","location","Area / city")+field("Budget","budget","ETB or quote", "text",false)+field("When needed","when","Date / timing", "text",false)+field("Requirements","requirements","Important requirements")+field("Additional details","details","Anything else","text",false);
 document.getElementById("categoryPanel").innerHTML=`<div class="form-card listing-form-wrap"><div class="form-heading"><div><span class="kicker">${seller?"SELLER / POST":"BUYER / REQUEST"}</span><h3>${seller?"Create a clear listing":"Tell us what you are looking for"}</h3><p>Complete the form once. Add a photo if you have one. Your information can be prepared for review and social sharing.</p></div><span class="form-chip">${title}</span></div><form id="categoryForm">${fields}<label>Full name<input name="name" required autocomplete="name"></label><label>Phone number<input name="phone" required autocomplete="tel"></label><label>Telegram / WhatsApp<input name="contact" placeholder="@username or number" required></label><label>Photo ${seller?"(optional)":"(optional)"}<input id="categoryPhoto" name="photo" type="file" accept="image/*"></label><small class="muted">Your selected photo stays on your device until you choose a share/send action.</small><div class="form-actions"><button class="btn btn-primary" type="submit">Prepare submission</button><button class="btn btn-light" type="button" onclick="showCategoryForm('${key}','${seller?'buyer':'seller'}')">Switch to ${seller?'Buyer':'Seller'}</button></div><div id="categoryResult" class="order-result"></div></form></div>`;
 document.getElementById("categoryForm").addEventListener("submit",e=>handleCategorySubmit(e,key,mode));
}
async function handleCategorySubmit(e,key,mode){e.preventDefault();const fd=new FormData(e.target);const data={};for(const [k,v] of fd.entries())if(k!=="photo")data[k]=String(v).trim();const photo=document.getElementById("categoryPhoto")?.files?.[0];const title=categoryData[key].title;const role=mode==="seller"?"Seller listing":"Buyer request";let msg=`Trust Market — ${role}\nCategory: ${title}\n\n`;Object.entries(data).forEach(([k,v])=>{if(v)msg+=`${labelize(k)}: ${v}\n`});const result=document.getElementById("categoryResult");result.innerHTML=`<div class="result-actions"><button class="btn btn-primary" id="shareListingBtn">Share / Send</button><a class="btn btn-light" target="_blank" rel="noopener" href="https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent(msg)}">WhatsApp</a><a class="btn btn-light" target="_blank" rel="noopener" href="https://t.me/share/url?url=${encodeURIComponent(window.location.href.split("#")[0])}&text=${encodeURIComponent(msg)}">Telegram</a><a class="btn btn-light" target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href.split("#")[0])}">Facebook</a></div><div class="privacy-note">🔒 Your personal phone number is used for verification only. It will not be shown on the public listing after approval. Buyers and sellers contact Trust Market through the page contact channels.</div><p class="muted">If your phone supports file sharing, “Share / Send” can include the selected photo. The social buttons share the listing page; public contact details remain protected.</p>`;document.getElementById("shareListingBtn").onclick=async()=>{const ok=await nativeShare({title:`${title} — Trust Market`,text:msg,url:window.location.href.split("#")[0],image:photo?URL.createObjectURL(photo):null});if(!ok)toast("Use WhatsApp or the social share buttons")};toast("Submission prepared")}
function labelize(k){return k.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())}
function openImage(src,title){const m=document.createElement("div");m.className="modal";m.innerHTML=`<div class="modal-card image-modal"><button class="close" onclick="this.closest('.modal').remove()">×</button><img src="${src}" alt="${esc(title)}"><h3>${esc(title)}</h3></div>`;m.onclick=e=>{if(e.target===m)m.remove()};document.body.appendChild(m)}
function openPayment(target,qty=1){let p=products.find(x=>x.id===target);const amount=p?p.price*qty:cart.reduce((a,x)=>a+x.price*x.qty,0);const title=p?p.name:"Your ETCARE order";const m=document.getElementById("paymentModal");m.className="modal";m.innerHTML=`<div class="modal-card payment-modal"><button class="close" onclick="closePayment()">×</button><span class="kicker">PAYMENT</span><h2>${esc(title)}</h2><div class="payment-total">${p?`${qty} × ${money(p.price)} = <strong>${money(amount)}</strong>`:`Total: <strong>${money(amount)}</strong>`}</div><p class="muted">Choose one payment option. The payment details are revealed only when you open the option.</p><div class="payment-options"><button class="payment-link" onclick="showPaymentDetails('telebirr','${p?p.id:'cart'}',${qty})"><span>📱</span><b>Telebirr</b><small>Open payment details</small><i>→</i></button><button class="payment-link" onclick="showPaymentDetails('cbe','${p?p.id:'cart'}',${qty})"><span>🏦</span><b>CBE</b><small>Open payment details</small><i>→</i></button></div><div class="notice">Never enter your PIN, password or OTP on Trust Market.</div></div>`}
function showPaymentDetails(method,productId,qty){const p=products.find(x=>x.id===productId);const isTele=method==="telebirr";const holder="Guesh Gebreabzgi";const guide=isTele?CONFIG.telebirrGuide:CONFIG.cbeGuide;const amount=p?p.price*qty:cart.reduce((a,x)=>a+x.price*x.qty,0);const m=document.getElementById("paymentModal");m.innerHTML=`<div class="modal-card payment-modal"><button class="close" onclick="closePayment()">×</button><span class="kicker">${isTele?"TELEBIRR":"CBE"} PAYMENT</span><h2>Payment ready</h2><div class="payment-total">Amount: <strong>${money(amount)}</strong></div><div class="payment-detail"><b>${isTele?"Telebirr":"CBE"}</b><small>${holder}</small><span class="masked-account">Payment details are protected</span></div><a class="btn btn-primary full" href="${guide}" target="_blank" rel="noopener">Open official ${isTele?"Telebirr":"CBE"}</a><button class="btn btn-light full" onclick="goToCheckout('${method}')">Continue to verification</button><p class="notice">For security, Trust Market does not display or copy account numbers. Complete payment only through the official ${isTele?"Telebirr":"CBE"} channel. Never enter your PIN, password or OTP here.</p></div>`}
function goToCheckout(method){closePayment();document.querySelector('#orderForm select[name="method"]').value=method==="cbe"?"CBE":"Telebirr";location.hash="checkout"}
function closePayment(){document.getElementById("paymentModal").className="modal hidden"}

function buyAllFive(){const bundleTotal=products.reduce((a,p)=>a+p.price,0);const discounted=Math.round((bundleTotal*0.9)*100)/100;const m=document.getElementById("paymentModal");m.className="modal";m.innerHTML=`<div class="modal-card payment-modal"><button class="close" onclick="closePayment()">×</button><span class="kicker">5-PRODUCT OFFER</span><h2>All 5 ETCARE products</h2><div class="payment-total"><del>${money(bundleTotal)}</del> <strong>${money(discounted)}</strong></div><p class="muted">Buy all five products and receive 10% discount.</p><div class="payment-detail"><b>10% discount</b><small>Final total: ${money(discounted)}</small></div><div class="payment-options"><button class="payment-link" onclick="showBundlePayment('telebirr',${discounted})"><span>📱</span><b>Telebirr</b><small>Open payment details</small><i>→</i></button><button class="payment-link" onclick="showBundlePayment('cbe',${discounted})"><span>🏦</span><b>CBE</b><small>Open payment details</small><i>→</i></button></div><div class="notice">Trust Market never asks for your PIN, password or OTP.</div></div>`}
function showBundlePayment(method,amount){const isTele=method==="telebirr";const holder="Guesh Gebreabzgi";const guide=isTele?CONFIG.telebirrGuide:CONFIG.cbeGuide;const m=document.getElementById("paymentModal");m.innerHTML=`<div class="modal-card payment-modal"><button class="close" onclick="closePayment()">×</button><span class="kicker">${isTele?"TELEBIRR":"CBE"} PAYMENT</span><h2>5-product offer</h2><div class="payment-total">Amount: <strong>${money(amount)}</strong></div><div class="payment-detail"><b>${isTele?"Telebirr":"CBE"}</b><small>${holder}</small><span class="masked-account">Payment details are protected</span></div><a class="btn btn-primary full" href="${guide}" target="_blank" rel="noopener">Open official ${isTele?"Telebirr":"CBE"}</a><button class="btn btn-light full" onclick="goToBundleCheckout('${method}',${amount})">Continue to verification</button><p class="notice">Account numbers are not displayed or copied on Trust Market. Never enter your PIN, password or OTP here.</p></div>`}
function goToBundleCheckout(method,amount){closePayment();document.querySelector('#orderForm select[name="method"]').value=method==="cbe"?"CBE":"Telebirr";document.getElementById("orderDetails").value=`ETCARE 5-PRODUCT OFFER — 10% DISCOUNT — ${money(amount)}`;location.hash="checkout"}
function openBusinessPackage(){const m=document.getElementById("paymentModal");m.className="modal";m.innerHTML=`<div class="modal-card business-modal"><button class="close" onclick="closePayment()">×</button><span class="kicker">BUSINESS PACKAGE</span><h2>Choose your package</h2><p class="muted">The Business Package is a separate opportunity from individual ETCARE shopping. Package customers receive the business-opportunity system, company training, sales/life-skills training and network-marketing training at no additional training fee.</p><div class="package-list"><label class="package-option"><input type="radio" name="pkg" value="Gold"><span><b>Gold</b><strong>17,899 ETB</strong></span><small>Select</small></label><label class="package-option"><input type="radio" name="pkg" value="Ziva"><span><b>Ziva</b><strong>13,989 ETB</strong></span><small>Select</small></label><label class="package-option"><input type="radio" name="pkg" value="Glow"><span><b>Glow</b><strong>9,989 ETB</strong></span><small>Select</small></label></div><div class="company-payment-note"><span>Payment destination</span><b>CBE</b><strong>${esc(CONFIG.companyHolder)}</strong><small>Company account details are revealed only after a package is selected.</small></div><button class="btn btn-primary full" onclick="continuePackage()">Continue with selected package</button><p class="notice">For security, never enter a PIN, password or OTP on Trust Market.</p></div>`}
function continuePackage(){const selected=document.querySelector('input[name="pkg"]:checked');if(!selected){toast("Choose Gold, Ziva or Glow first");return}const prices={Gold:17899,Ziva:13989,Glow:9989};const name=selected.value;const m=document.getElementById("paymentModal");m.innerHTML=`<div class="modal-card business-modal"><button class="close" onclick="closePayment()">×</button><span class="kicker">${name.toUpperCase()} PACKAGE</span><h2>${name} — ${money(prices[name])}</h2><div class="company-account-box"><span>CBE • COMPANY PAYMENT</span><b>${esc(CONFIG.companyHolder)}</b><small>Account number is not displayed on Trust Market.</small></div><p class="muted">Complete the package payment through the official CBE channel, keep the receipt, then send the receipt and your contact details to Trust Market.</p><a class="btn btn-primary full" href="${CONFIG.cbeGuide}" target="_blank" rel="noopener">Open CBE</a><button class="btn btn-light full" onclick="openPackageVerification('${name}',${prices[name]})">Continue to verification</button><div class="notice">Trust Market does not display or copy the company account number. Never enter a PIN, password or OTP here.</div></div>`}
function openPackageVerification(pkg,price){closePayment();const f=document.getElementById("orderForm");f.querySelector('[name="method"]').value="CBE";document.getElementById("orderDetails").value=`BUSINESS PACKAGE — ${pkg} — ${money(price)}`;location.hash="checkout";setTimeout(()=>toast("Package selected. Complete payment, then prepare verification."),300)}
function setReviewStars(n){document.getElementById("reviewRating").value=n;document.querySelectorAll("#starPicker button").forEach(b=>b.classList.toggle("active",+b.dataset.star<=n))}
function renderReviews(){const count=reviews.length,avg=count?reviews.reduce((a,r)=>a+r.rating,0)/count:0;document.getElementById("ratingAverage").textContent=count?avg.toFixed(1):"—";document.getElementById("ratingStars").textContent=count?"★".repeat(Math.round(avg))+"☆".repeat(5-Math.round(avg)):"☆☆☆☆☆";document.getElementById("ratingCount").textContent=count?`${count} rating${count===1?"":"s"}`:"No ratings yet";document.getElementById("reviewList").innerHTML=reviews.slice().reverse().slice(0,6).map(r=>`<article class="review-item"><div class="stars">${"★".repeat(r.rating)}${"☆".repeat(5-r.rating)}</div><b>${esc(r.name)}</b><p>${esc(r.text)}</p></article>`).join("")}
document.querySelectorAll("#starPicker button").forEach(b=>b.addEventListener("click",()=>setReviewStars(+b.dataset.star)));setReviewStars(5);
document.getElementById("reviewForm").addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("reviewName").value.trim(),rating=+document.getElementById("reviewRating").value,text=document.getElementById("reviewText").value.trim();reviews.push({name,rating,text});localStorage.setItem("trust_market_reviews",JSON.stringify(reviews));renderReviews();const msg=`Trust Market Review\nName: ${name}\nRating: ${rating}/5\nFeedback: ${text}`;document.getElementById("reviewText").value="";document.getElementById("reviewForm").insertAdjacentHTML("beforeend",`<div class="result-actions"><a class="btn btn-primary" target="_blank" rel="noopener" href="https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent(msg)}">Send review by WhatsApp</a><button class="btn btn-light" type="button" onclick="nativeShare({title:'Trust Market review',text:${JSON.stringify(msg)},url:window.location.href})">Share</button></div>`);toast("Review prepared")});
document.getElementById("language").addEventListener("change",e=>{const lang=e.target.value;document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(t[lang]?.[k])el.textContent=t[lang][k]});document.documentElement.dir=lang==="ar"?"rtl":"ltr"});
document.getElementById("orderForm").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),name=f.get("name"),phone=f.get("phone"),contact=f.get("contact")||"",method=f.get("method"),details=f.get("details"),file=document.getElementById("receiptFile")?.files?.[0];const msg=`Trust Market Order Verification\nName: ${name}\nPhone: ${phone}\nContact: ${contact}\nPayment: ${method}\nOrder: ${details}\nReceipt: ${file?file.name:"No screenshot selected"}`;document.getElementById("orderResult").innerHTML=`<div class="result-actions"><a class="btn btn-primary" target="_blank" rel="noopener" href="https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent(msg)}">Open WhatsApp</a><button class="btn btn-light" type="button" id="shareOrderBtn">Share / Send</button></div><p class="muted">If your phone supports file sharing, Share / Send can include the selected receipt image.</p>`;document.getElementById("shareOrderBtn").onclick=()=>nativeShare({title:"Trust Market Order Verification",text:msg,url:window.location.href,image:file?URL.createObjectURL(file):null});toast("Verification message prepared")});
renderProducts();renderCart();renderReviews();
